import { z } from "zod";
import { db } from "@/lib/db";
import { issueApiKey,type ApiScope } from "@/lib/developer-api";
import { jsonError } from "@/lib/http";
import { auditPlatform,requirePlatform } from "@/lib/platform";

const tenantId=z.string().regex(/^[a-z0-9-]{3,40}$/),settingsSchema=z.object({tenantId,enabled:z.boolean(),schoolVisible:z.boolean(),allowRead:z.boolean(),allowWrite:z.boolean(),requestsPerMinute:z.number().int().min(10).max(1000)}),keySchema=z.object({tenantId,name:z.string().trim().min(2).max(80),scopes:z.array(z.enum(["read","write"])).min(1).max(2),expiresAt:z.string().date().nullable().default(null)}),deleteSchema=z.string().uuid();
function validSchool(id:string){return Boolean(db.prepare("SELECT 1 FROM tenants WHERE id=? AND id!='platform'").get(id))}
export async function GET(){const auth=await requirePlatform();if("error" in auth)return auth.error;const schools=db.prepare(`SELECT t.id,t.name,t.plan,t.license_status licenseStatus,t.active,s.enabled,s.school_visible schoolVisible,s.allow_read allowRead,s.allow_write allowWrite,s.requests_per_minute requestsPerMinute,(SELECT COUNT(*) FROM developer_api_keys k WHERE k.tenant_id=t.id AND k.active=1 AND (k.expires_at IS NULL OR datetime(k.expires_at)>=datetime('now'))) activeKeys FROM tenants t JOIN developer_api_settings s ON s.tenant_id=t.id WHERE t.id!='platform' ORDER BY t.name`).all();const keys=(db.prepare("SELECT id,tenant_id tenantId,name,key_prefix prefix,scopes,active,expires_at expiresAt,last_used_at lastUsedAt,created_at createdAt FROM developer_api_keys WHERE tenant_id!='platform' ORDER BY created_at DESC LIMIT 500").all() as Array<{scopes:string}>).map(row=>({...row,scopes:JSON.parse(row.scopes)}));const logs=db.prepare("SELECT l.id,l.tenant_id tenantId,k.name keyName,l.method,l.path,l.status,l.created_at createdAt FROM developer_api_logs l LEFT JOIN developer_api_keys k ON k.id=l.key_id ORDER BY l.created_at DESC LIMIT 100").all();return Response.json({data:{schools,keys,logs}},{headers:{"Cache-Control":"no-store"}})}
export async function PATCH(request:Request){const auth=await requirePlatform(request);if("error" in auth)return auth.error;const body=settingsSchema.safeParse(await request.json().catch(()=>null));if(!body.success||!validSchool(body.data?.tenantId||""))return jsonError("Invalid school API settings",400,body.success?undefined:body.error.flatten());const value=body.data;if(value.allowWrite&&!value.allowRead)return jsonError("Write-enabled integrations must also retain read access",400);db.prepare("UPDATE developer_api_settings SET enabled=?,school_visible=?,allow_read=?,allow_write=?,requests_per_minute=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=?").run(Number(value.enabled),Number(value.schoolVisible),Number(value.allowRead),Number(value.allowWrite),value.requestsPerMinute,value.tenantId);auditPlatform(auth.session.userId,"developer_api.settings_updated",value.tenantId,{enabled:value.enabled,schoolVisible:value.schoolVisible,allowRead:value.allowRead,allowWrite:value.allowWrite,requestsPerMinute:value.requestsPerMinute});return Response.json({data:value})}
export async function POST(request:Request){const auth=await requirePlatform(request);if("error" in auth)return auth.error;const body=keySchema.safeParse(await request.json().catch(()=>null));if(!body.success||!validSchool(body.data?.tenantId||""))return jsonError("Invalid API key request",400,body.success?undefined:body.error.flatten());const settings=db.prepare("SELECT enabled,allow_read allowRead,allow_write allowWrite FROM developer_api_settings WHERE tenant_id=?").get(body.data.tenantId) as {enabled:number;allowRead:number;allowWrite:number};if(!settings.enabled)return jsonError("Enable the school developer API before issuing a key",409);if(body.data.scopes.includes("read")&&!settings.allowRead||body.data.scopes.includes("write")&&!settings.allowWrite)return jsonError("Requested key scopes exceed the school API policy",403);const created=issueApiKey(body.data.tenantId,body.data.name,body.data.scopes as ApiScope[],auth.session.userId,body.data.expiresAt);auditPlatform(auth.session.userId,"developer_api.key_created",body.data.tenantId,{keyId:created.id,name:body.data.name,scopes:body.data.scopes,expiresAt:body.data.expiresAt});return Response.json({data:{...created,name:body.data.name,scopes:body.data.scopes,expiresAt:body.data.expiresAt,warning:"Copy this key now. It cannot be shown again."}},{status:201})}
export async function DELETE(request:Request){const auth=await requirePlatform(request);if("error" in auth)return auth.error;const id=deleteSchema.safeParse(new URL(request.url).searchParams.get("key"));if(!id.success)return jsonError("Invalid API key",400);const row=db.prepare("SELECT tenant_id tenantId,name FROM developer_api_keys WHERE id=? AND tenant_id!='platform'").get(id.data) as {tenantId:string;name:string}|undefined;if(!row)return jsonError("API key not found",404);db.prepare("UPDATE developer_api_keys SET active=0 WHERE id=?").run(id.data);auditPlatform(auth.session.userId,"developer_api.key_revoked",row.tenantId,{keyId:id.data,name:row.name});return new Response(null,{status:204})}
