import { createHash,randomBytes,randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import { getClientIp,jsonError,rateLimit } from "@/lib/http";

export type ApiScope="read"|"write";
export type DeveloperApiAuth={keyId:string;tenantId:string;scopes:ApiScope[];rateLimit:number};
export const apiDatasets=["students","teachers","parents","subjects","classes","lessons","exams","assignments","results","attendance","events","messages","announcements","submissions","gamification"] as const;
export type ApiDataset=typeof apiDatasets[number];

export function hashApiKey(key:string){return createHash("sha256").update(key).digest("hex")}
export function issueApiKey(tenantId:string,name:string,scopes:ApiScope[],createdBy:string,expiresAt:string|null){const secret=`sime_live_${randomBytes(24).toString("base64url")}`,id=randomUUID(),prefix=secret.slice(0,18);db.prepare("INSERT INTO developer_api_keys (id,tenant_id,name,key_prefix,key_hash,scopes,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?)").run(id,tenantId,name,prefix,hashApiKey(secret),JSON.stringify(scopes),expiresAt,createdBy);return {id,key:secret,prefix}}

export async function requireDeveloperApi(request:Request,scope:ApiScope){const supplied=(request.headers.get("x-api-key")||request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"").trim();if(!/^sime_live_[A-Za-z0-9_-]{20,}$/.test(supplied))return {error:jsonError("A valid API key is required",401)} as const;const row=db.prepare(`SELECT k.id keyId,k.tenant_id tenantId,k.scopes,s.enabled,s.allow_read allowRead,s.allow_write allowWrite,s.requests_per_minute rateLimit,t.active,t.license_status licenseStatus,t.license_expires_at licenseExpiresAt FROM developer_api_keys k JOIN developer_api_settings s ON s.tenant_id=k.tenant_id JOIN tenants t ON t.id=k.tenant_id WHERE k.key_hash=? AND k.active=1 AND (k.expires_at IS NULL OR datetime(k.expires_at)>=datetime('now'))`).get(hashApiKey(supplied)) as {keyId:string;tenantId:string;scopes:string;enabled:number;allowRead:number;allowWrite:number;rateLimit:number;active:number;licenseStatus:string;licenseExpiresAt:string|null}|undefined;if(!row)return {error:jsonError("API key is invalid, expired, or revoked",401)} as const;const licensed=row.active&&["trial","active"].includes(row.licenseStatus)&&(!row.licenseExpiresAt||new Date(row.licenseExpiresAt)>=new Date());if(!licensed||!row.enabled)return {error:jsonError("Developer API access is disabled for this school or license",403)} as const;const scopes=JSON.parse(row.scopes) as ApiScope[];if(!scopes.includes(scope)||(scope==="read"&&!row.allowRead)||(scope==="write"&&!row.allowWrite))return {error:jsonError(`This API key does not have ${scope} access`,403)} as const;const limited=rateLimit(`developer-api:${row.keyId}`,row.rateLimit);if(!limited.allowed)return {error:jsonError("API rate limit exceeded",429,{retryAfter:limited.retryAfter})} as const;db.prepare("UPDATE developer_api_keys SET last_used_at=CURRENT_TIMESTAMP WHERE id=?").run(row.keyId);return {auth:{keyId:row.keyId,tenantId:row.tenantId,scopes,rateLimit:row.rateLimit} satisfies DeveloperApiAuth} as const}

export function logDeveloperApi(auth:DeveloperApiAuth,request:Request,status:number){db.prepare("INSERT INTO developer_api_logs (key_id,tenant_id,method,path,status,ip) VALUES (?,?,?,?,?,?)").run(auth.keyId,auth.tenantId,request.method,new URL(request.url).pathname,status,getClientIp(request))}
export function apiResponse(auth:DeveloperApiAuth,request:Request,data:unknown,status=200,meta?:Record<string,unknown>){logDeveloperApi(auth,request,status);return Response.json({data,...meta?{meta}:{}},{status,headers:{"Cache-Control":"no-store","X-RateLimit-Limit":String(auth.rateLimit)}})}
