export const languages = [
  { code: "en", label: "English", native: "English", direction: "ltr" },
  { code: "ar", label: "Arabic", native: "العربية", direction: "rtl" },
  { code: "fr", label: "French", native: "Français", direction: "ltr" },
  { code: "bn", label: "Bengali", native: "বাংলা", direction: "ltr" },
  { code: "es", label: "Spanish", native: "Español", direction: "ltr" },
] as const;

export type Language = typeof languages[number]["code"];
export type TranslationKey = keyof typeof english;

const english = {
  language: "Language", home: "Home", overview: "Overview", schools: "Schools", licenses: "Licenses", schoolUsers: "School users",
  developerApi: "Developer API", auditLog: "Audit log", platformSettings: "Platform settings", sageAi: "SAGE AI", idCards: "ID Cards",
  teachers: "Teachers", students: "Students", parents: "Parents", earlyIntervention: "Early intervention", academy: "Academy",
  subjects: "Subjects", classes: "Classes", lessons: "Lessons", exams: "Exams", assignments: "Assignments", results: "Results",
  attendance: "Attendance", gamification: "Gamification", overallClass: "Overall & class", gameRules: "Game rules", events: "Events",
  messages: "Messages", announcements: "Announcements", profile: "Profile", settings: "Settings", logout: "Log out",
  openMenu: "Open main menu", closeMenu: "Close menu", closeNavigation: "Close navigation", mainNavigation: "Main navigation",
  dashboardHome: "Dashboard home", openProfile: "Open profile", search: "Search school records…", notifications: "Notifications",
  welcome: "Welcome To Gamified School", signInDescription: "Sign in as a school administrator, teacher, student, or parent.",
  tryDemo: "Try a demo role", admin: "Admin", teacher: "Teacher", student: "Student", parent: "Parent", superadmin: "Super admin",
  schoolId: "School ID", email: "Email", password: "Password", show: "Show", hide: "Hide", signingIn: "Signing in…",
  schoolLogin: "School login", platformLoginLink: "Platform super administrator sign in", restrictedAccess: "Restricted platform access",
  superadminSignIn: "Super-admin sign in", platformDescription: "Monitor isolated school instances and platform health. School administrators and other school roles must use the regular school login.",
  platformEmail: "Platform email", enterPlatform: "Enter platform console", returnSchool: "Return to school login",
  identityCenter: "Identity center", smartCards: "School identity cards", cardHelp: "Print exact-size cards on an A4 cut sheet or save them as PDF.",
  chooseIdentity: "Choose an authorized identity", printSelected: "Print selected", printAll: "Print all", noIdentity: "No identity record is available.",
  printPreview: "ID card print preview", officialId: "Official identification", cardHolder: "Card holder", idNumber: "ID number",
  bloodType: "Blood type", grade: "Grade", class: "Class", scanVerify: "Scan to verify", academicYear: "Academic year", secureId: "SIME Secure ID",
  card: "card", cards: "cards", platformIdentity: "Platform identity", staffIdentity: "Staff identity", guardianIdentity: "Guardian identity",
  searchSystem:"Search the school system",searchPlaceholder:"What do you want to find?",searchResults:"Search results",typeTwo:"Type at least two characters.",searching:"Searching your workspace…",noResults:"No authorized results found.",navigateOpen:"Navigate · Enter open",escClose:"Esc close",
} as const;

const dictionaries: Record<Language, Partial<Record<TranslationKey,string>>> = {
  en: english,
  ar: {
    language:"اللغة",home:"الرئيسية",overview:"نظرة عامة",schools:"المدارس",licenses:"التراخيص",schoolUsers:"مستخدمو المدارس",developerApi:"واجهة المطور",auditLog:"سجل التدقيق",platformSettings:"إعدادات المنصة",sageAi:"مساعد SAGE",idCards:"بطاقات الهوية",teachers:"المعلمون",students:"الطلاب",parents:"أولياء الأمور",earlyIntervention:"التدخل المبكر",academy:"الأكاديمية",subjects:"المواد",classes:"الفصول",lessons:"الدروس",exams:"الاختبارات",assignments:"الواجبات",results:"النتائج",attendance:"الحضور",gamification:"التحفيز",overallClass:"العام والفصل",gameRules:"قواعد النقاط",events:"الفعاليات",messages:"الرسائل",announcements:"الإعلانات",profile:"الملف الشخصي",settings:"الإعدادات",logout:"تسجيل الخروج",openMenu:"فتح القائمة الرئيسية",closeMenu:"إغلاق القائمة",closeNavigation:"إغلاق التنقل",mainNavigation:"التنقل الرئيسي",dashboardHome:"الرئيسية",openProfile:"فتح الملف الشخصي",search:"البحث في سجلات المدرسة…",notifications:"الإشعارات",welcome:"مرحباً بكم في المدرسة التفاعلية",signInDescription:"سجّل الدخول كمدير مدرسة أو معلم أو طالب أو ولي أمر.",tryDemo:"جرّب دوراً تجريبياً",admin:"مدير",teacher:"معلم",student:"طالب",parent:"ولي أمر",superadmin:"المدير العام",schoolId:"معرّف المدرسة",email:"البريد الإلكتروني",password:"كلمة المرور",show:"إظهار",hide:"إخفاء",signingIn:"جارٍ تسجيل الدخول…",schoolLogin:"دخول المدرسة",platformLoginLink:"دخول المدير العام للمنصة",restrictedAccess:"وصول مقيّد للمنصة",superadminSignIn:"دخول المدير العام",platformDescription:"راقب المدارس المعزولة وصحة المنصة. يجب على مديري المدارس وبقية الأدوار استخدام تسجيل دخول المدرسة.",platformEmail:"بريد المنصة",enterPlatform:"دخول لوحة المنصة",returnSchool:"العودة إلى دخول المدرسة",identityCenter:"مركز الهوية",smartCards:"بطاقات الهوية المدرسية",cardHelp:"اطبع البطاقات بالحجم الفعلي على ورقة A4 أو احفظها بصيغة PDF.",chooseIdentity:"اختر هوية مصرحاً بها",printSelected:"طباعة المحدد",printAll:"طباعة الكل",noIdentity:"لا يوجد سجل هوية متاح.",printPreview:"معاينة طباعة بطاقة الهوية",officialId:"هوية رسمية",cardHolder:"حامل البطاقة",idNumber:"رقم الهوية",bloodType:"فصيلة الدم",grade:"الصف",class:"الفصل",scanVerify:"امسح للتحقق",academicYear:"العام الدراسي",secureId:"هوية SIME الآمنة",card:"بطاقة",cards:"بطاقات",platformIdentity:"هوية المنصة",staffIdentity:"هوية الموظف",guardianIdentity:"هوية ولي الأمر",searchSystem:"البحث في نظام المدرسة",searchPlaceholder:"ما الذي تريد البحث عنه؟",searchResults:"نتائج البحث",typeTwo:"اكتب حرفين على الأقل.",searching:"جارٍ البحث في مساحة العمل…",noResults:"لم يتم العثور على نتائج مصرح بها.",navigateOpen:"تنقّل · Enter للفتح",escClose:"Esc للإغلاق"
  },
  fr: {
    language:"Langue",home:"Accueil",overview:"Vue d’ensemble",schools:"Écoles",licenses:"Licences",schoolUsers:"Utilisateurs",developerApi:"API développeur",auditLog:"Journal d’audit",platformSettings:"Paramètres plateforme",sageAi:"IA SAGE",idCards:"Cartes d’identité",teachers:"Enseignants",students:"Élèves",parents:"Parents",earlyIntervention:"Intervention précoce",academy:"Académie",subjects:"Matières",classes:"Classes",lessons:"Leçons",exams:"Examens",assignments:"Devoirs",results:"Résultats",attendance:"Présences",gamification:"Ludification",overallClass:"Général et classe",gameRules:"Règles de jeu",events:"Événements",messages:"Messages",announcements:"Annonces",profile:"Profil",settings:"Paramètres",logout:"Déconnexion",openMenu:"Ouvrir le menu principal",closeMenu:"Fermer le menu",closeNavigation:"Fermer la navigation",mainNavigation:"Navigation principale",dashboardHome:"Accueil du tableau de bord",openProfile:"Ouvrir le profil",search:"Rechercher dans les dossiers…",notifications:"Notifications",welcome:"Bienvenue à l’école ludique",signInDescription:"Connectez-vous comme administrateur, enseignant, élève ou parent.",tryDemo:"Essayer un rôle démo",admin:"Administrateur",teacher:"Enseignant",student:"Élève",parent:"Parent",superadmin:"Super administrateur",schoolId:"Identifiant de l’école",email:"E-mail",password:"Mot de passe",show:"Afficher",hide:"Masquer",signingIn:"Connexion…",schoolLogin:"Connexion école",platformLoginLink:"Connexion super administrateur",restrictedAccess:"Accès plateforme restreint",superadminSignIn:"Connexion super administrateur",platformDescription:"Surveillez les écoles isolées et la santé de la plateforme. Les autres rôles utilisent la connexion école.",platformEmail:"E-mail plateforme",enterPlatform:"Entrer dans la plateforme",returnSchool:"Retour à la connexion école",identityCenter:"Centre d’identité",smartCards:"Cartes d’identité scolaires",cardHelp:"Imprimez les cartes à taille réelle sur une feuille A4 ou enregistrez-les en PDF.",chooseIdentity:"Choisir une identité autorisée",printSelected:"Imprimer la sélection",printAll:"Tout imprimer",noIdentity:"Aucun dossier d’identité disponible.",printPreview:"Aperçu d’impression",officialId:"Identification officielle",cardHolder:"Titulaire",idNumber:"Numéro d’identité",bloodType:"Groupe sanguin",grade:"Niveau",class:"Classe",scanVerify:"Scanner pour vérifier",academicYear:"Année scolaire",secureId:"Identité SIME sécurisée",card:"carte",cards:"cartes",platformIdentity:"Identité plateforme",staffIdentity:"Identité du personnel",guardianIdentity:"Identité du parent"
  },
  bn: {
    language:"ভাষা",home:"হোম",overview:"সারসংক্ষেপ",schools:"স্কুলসমূহ",licenses:"লাইসেন্স",schoolUsers:"স্কুল ব্যবহারকারী",developerApi:"ডেভেলপার API",auditLog:"অডিট লগ",platformSettings:"প্ল্যাটফর্ম সেটিংস",sageAi:"SAGE AI",idCards:"পরিচয়পত্র",teachers:"শিক্ষক",students:"শিক্ষার্থী",parents:"অভিভাবক",earlyIntervention:"প্রাথমিক সহায়তা",academy:"একাডেমি",subjects:"বিষয়",classes:"শ্রেণি",lessons:"পাঠ",exams:"পরীক্ষা",assignments:"অ্যাসাইনমেন্ট",results:"ফলাফল",attendance:"উপস্থিতি",gamification:"গেমিফিকেশন",overallClass:"সামগ্রিক ও শ্রেণি",gameRules:"গেমের নিয়ম",events:"ইভেন্ট",messages:"বার্তা",announcements:"ঘোষণা",profile:"প্রোফাইল",settings:"সেটিংস",logout:"লগ আউট",openMenu:"মূল মেনু খুলুন",closeMenu:"মেনু বন্ধ করুন",closeNavigation:"নেভিগেশন বন্ধ করুন",mainNavigation:"মূল নেভিগেশন",dashboardHome:"ড্যাশবোর্ড হোম",openProfile:"প্রোফাইল খুলুন",search:"স্কুল রেকর্ড খুঁজুন…",notifications:"বিজ্ঞপ্তি",welcome:"গেমিফাইড স্কুলে স্বাগতম",signInDescription:"স্কুল প্রশাসক, শিক্ষক, শিক্ষার্থী বা অভিভাবক হিসেবে সাইন ইন করুন।",tryDemo:"ডেমো ভূমিকা চেষ্টা করুন",admin:"প্রশাসক",teacher:"শিক্ষক",student:"শিক্ষার্থী",parent:"অভিভাবক",superadmin:"সুপার অ্যাডমিন",schoolId:"স্কুল আইডি",email:"ইমেইল",password:"পাসওয়ার্ড",show:"দেখান",hide:"লুকান",signingIn:"সাইন ইন হচ্ছে…",schoolLogin:"স্কুল লগইন",platformLoginLink:"প্ল্যাটফর্ম সুপার অ্যাডমিন লগইন",restrictedAccess:"সীমিত প্ল্যাটফর্ম প্রবেশ",superadminSignIn:"সুপার অ্যাডমিন সাইন ইন",platformDescription:"স্বতন্ত্র স্কুল ও প্ল্যাটফর্মের অবস্থা পর্যবেক্ষণ করুন। অন্যান্য ভূমিকা স্কুল লগইন ব্যবহার করবে।",platformEmail:"প্ল্যাটফর্ম ইমেইল",enterPlatform:"প্ল্যাটফর্ম কনসোলে প্রবেশ",returnSchool:"স্কুল লগইনে ফিরুন",identityCenter:"পরিচয় কেন্দ্র",smartCards:"স্কুল পরিচয়পত্র",cardHelp:"A4 পাতায় সঠিক মাপে কার্ড প্রিন্ট করুন অথবা PDF হিসেবে সংরক্ষণ করুন।",chooseIdentity:"অনুমোদিত পরিচয় বাছুন",printSelected:"নির্বাচিতটি প্রিন্ট",printAll:"সব প্রিন্ট",noIdentity:"কোনো পরিচয় রেকর্ড নেই।",printPreview:"পরিচয়পত্র প্রিন্ট প্রিভিউ",officialId:"অফিসিয়াল পরিচয়",cardHolder:"কার্ডধারী",idNumber:"আইডি নম্বর",bloodType:"রক্তের গ্রুপ",grade:"গ্রেড",class:"শ্রেণি",scanVerify:"যাচাই করতে স্ক্যান করুন",academicYear:"শিক্ষাবর্ষ",secureId:"SIME সুরক্ষিত আইডি",card:"কার্ড",cards:"কার্ড",platformIdentity:"প্ল্যাটফর্ম পরিচয়",staffIdentity:"কর্মী পরিচয়",guardianIdentity:"অভিভাবক পরিচয়"
  },
  es: {
    language:"Idioma",home:"Inicio",overview:"Resumen",schools:"Escuelas",licenses:"Licencias",schoolUsers:"Usuarios escolares",developerApi:"API para desarrolladores",auditLog:"Registro de auditoría",platformSettings:"Configuración de plataforma",sageAi:"IA SAGE",idCards:"Tarjetas de identidad",teachers:"Profesores",students:"Estudiantes",parents:"Padres",earlyIntervention:"Intervención temprana",academy:"Academia",subjects:"Asignaturas",classes:"Clases",lessons:"Lecciones",exams:"Exámenes",assignments:"Tareas",results:"Resultados",attendance:"Asistencia",gamification:"Gamificación",overallClass:"General y clase",gameRules:"Reglas del juego",events:"Eventos",messages:"Mensajes",announcements:"Anuncios",profile:"Perfil",settings:"Configuración",logout:"Cerrar sesión",openMenu:"Abrir menú principal",closeMenu:"Cerrar menú",closeNavigation:"Cerrar navegación",mainNavigation:"Navegación principal",dashboardHome:"Inicio del panel",openProfile:"Abrir perfil",search:"Buscar registros escolares…",notifications:"Notificaciones",welcome:"Bienvenido a la escuela gamificada",signInDescription:"Inicia sesión como administrador, profesor, estudiante o padre.",tryDemo:"Probar un rol de demostración",admin:"Administrador",teacher:"Profesor",student:"Estudiante",parent:"Padre",superadmin:"Superadministrador",schoolId:"ID de la escuela",email:"Correo electrónico",password:"Contraseña",show:"Mostrar",hide:"Ocultar",signingIn:"Iniciando sesión…",schoolLogin:"Inicio de sesión escolar",platformLoginLink:"Inicio de superadministrador",restrictedAccess:"Acceso restringido",superadminSignIn:"Inicio de superadministrador",platformDescription:"Supervisa escuelas aisladas y la salud de la plataforma. Los demás roles deben usar el acceso escolar.",platformEmail:"Correo de plataforma",enterPlatform:"Entrar a la plataforma",returnSchool:"Volver al acceso escolar",identityCenter:"Centro de identidad",smartCards:"Tarjetas de identidad escolar",cardHelp:"Imprime tarjetas a tamaño real en una hoja A4 o guárdalas como PDF.",chooseIdentity:"Elegir identidad autorizada",printSelected:"Imprimir selección",printAll:"Imprimir todo",noIdentity:"No hay un registro de identidad disponible.",printPreview:"Vista previa de impresión",officialId:"Identificación oficial",cardHolder:"Titular",idNumber:"Número de identidad",bloodType:"Grupo sanguíneo",grade:"Grado",class:"Clase",scanVerify:"Escanear para verificar",academicYear:"Año académico",secureId:"ID seguro SIME",card:"tarjeta",cards:"tarjetas",platformIdentity:"Identidad de plataforma",staffIdentity:"Identidad del personal",guardianIdentity:"Identidad del padre"
  },
};

export function translate(language: Language, key: TranslationKey) {
  return dictionaries[language][key] || english[key];
}

export function isLanguage(value: string | null): value is Language {
  return languages.some(item=>item.code===value);
}
