"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { useLanguage } from "@/components/LanguageProvider";

export default function SignInPage(){
 const router=useRouter(),{t}=useLanguage();
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[tenantId,setTenantId]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[showPassword,setShowPassword]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();if(loading)return;setLoading(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,tenantId})}),payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error??"Connexion impossible");router.replace(payload.data.redirectTo);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Connexion au serveur scolaire impossible.");setLoading(false)}}
 const input="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-[#c88700] focus:ring-4 focus:ring-amber-100";
 return <main id="main-content" className="min-h-screen bg-white text-[#111b2f]"><div className="grid min-h-screen lg:grid-cols-2"><form onSubmit={submit} aria-describedby={error?"login-error":undefined} aria-busy={loading} className="relative flex flex-col justify-center px-7 py-10 sm:px-16 lg:px-[12%]"><div className="absolute end-6 top-6"><LanguageSwitcher/></div><Image src="/design/school-ing-logo.png" alt="School-InG · GNG GROUP" width={190} height={64} priority className="mb-12 h-16 w-auto self-start object-contain"/><h1 className="text-3xl font-bold">{t("welcome")}</h1><p className="mt-2 text-sm text-slate-600">{t("signInDescription")}</p><div className="mt-7 space-y-4"><label className="block text-xs font-semibold text-slate-700">{t("schoolId")}<input required autoComplete="organization" value={tenantId} onChange={event=>setTenantId(event.target.value)} className={input} dir="ltr" autoFocus/></label><label className="block text-xs font-semibold text-slate-700">{t("email")}<input required type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} className={input} dir="ltr"/></label><label className="block text-xs font-semibold text-slate-700">{t("password")}<span className="relative mt-2 block"><input required type={showPassword?"text":"password"} autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} className="min-h-12 w-full rounded-xl border border-slate-300 py-3 ps-4 pe-16 text-sm outline-none focus:border-[#c88700] focus:ring-4 focus:ring-amber-100"/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?t("hide"):t("show")} className="absolute inset-y-0 end-1 my-auto min-h-10 rounded-md px-3 text-xs font-bold text-slate-600 hover:bg-slate-100">{showPassword?t("hide"):t("show")}</button></span></label></div>{error&&<p id="login-error" role="alert" aria-live="assertive" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button type="submit" disabled={loading} className="mt-6 min-h-12 w-full rounded-xl bg-[#d89500] py-3 text-sm font-bold text-slate-950 hover:bg-[#e9a400] disabled:cursor-wait disabled:opacity-50">{loading?t("signingIn"):t("schoolLogin")}</button><Link href="/superadmin/sign-in" className="mt-4 min-h-11 text-center text-xs font-semibold text-[#765200] hover:underline">{t("platformLoginLink")}</Link></form><section aria-label="Accueil School-InG" className="hidden p-6 lg:block"><Image src="/design/auth-gradient.jpg" alt="Élèves dans un environnement scolaire coloré" width={720} height={990} priority className="h-full max-h-[calc(100vh-3rem)] w-full rounded-2xl object-cover"/></section></div></main>;
}
