import { apiDatasets } from "@/lib/developer-api";

const errorResponse=(description:string)=>({description,content:{"application/json":{schema:{$ref:"#/components/schemas/Error"}}}});

export async function GET(request:Request){
 const origin=new URL(request.url).origin;
 const spec={
  openapi:"3.1.0",
  info:{title:"School-InG Integration API",version:"1.0.0",description:"Licensed, tenant-isolated server-to-server API for school operational data."},
  servers:[{url:`${origin}/api/v1`}],
  security:[{ApiKeyAuth:[]}],
  paths:{
   "/data/{dataset}":{
    parameters:[{name:"dataset",in:"path",required:true,schema:{type:"string",enum:apiDatasets},description:"Operational dataset"}],
    get:{summary:"List and filter school records",operationId:"listDataset",parameters:[
     {name:"q",in:"query",schema:{type:"string",maxLength:80}},
     {name:"limit",in:"query",schema:{type:"integer",minimum:1,maximum:100,default:50}},
     {name:"offset",in:"query",schema:{type:"integer",minimum:0,maximum:10000,default:0}},
    ],responses:{"200":{$ref:"#/components/responses/SuccessList"},"401":{$ref:"#/components/responses/Unauthorized"},"403":{$ref:"#/components/responses/Forbidden"},"429":{$ref:"#/components/responses/RateLimited"}}},
    post:{summary:"Create a record in a school dataset",operationId:"createDatasetRecord",requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:true}}}},responses:{"201":{description:"Record created",content:{"application/json":{schema:{$ref:"#/components/schemas/Success"}}}},"400":{$ref:"#/components/responses/BadRequest"},"401":{$ref:"#/components/responses/Unauthorized"},"403":{$ref:"#/components/responses/Forbidden"},"409":{description:"Duplicate record or license capacity reached"},"429":{$ref:"#/components/responses/RateLimited"}}},
   },
  },
  components:{
   securitySchemes:{ApiKeyAuth:{type:"apiKey",in:"header",name:"X-API-Key",description:"API key generated by the School-InG platform super-admin. Bearer authentication is also accepted."}},
   schemas:{
    Success:{type:"object",required:["data"],properties:{data:{}}},
    Error:{type:"object",required:["error"],properties:{error:{type:"string"},details:{}}},
    StudentCreate:{type:"object",required:["studentId","name","email","grade","className"],properties:{studentId:{type:"string",example:"GIN-2026-2042"},name:{type:"string",example:"Mamadou Camara"},email:{type:"string",format:"email",example:"mamadou@ecole.gn"},phone:{type:"string",example:"+224 620 10 20 30"},grade:{type:"integer",minimum:1,maximum:12},className:{type:"string",example:"10e-A"},address:{type:"string",example:"Conakry, Guinée"},gender:{type:"string",enum:["female","male","other","unspecified"]}}},
   },
   responses:{
    SuccessList:{description:"Paginated dataset records",headers:{"X-RateLimit-Limit":{schema:{type:"integer"}}},content:{"application/json":{schema:{$ref:"#/components/schemas/Success"}}}},
    BadRequest:errorResponse("Request validation failed"),Unauthorized:errorResponse("API key missing, invalid, expired, or revoked"),Forbidden:errorResponse("License, API feature, or required scope is disabled"),RateLimited:errorResponse("Per-key request quota exceeded"),
   },
  },
 };
 return Response.json(spec,{headers:{"Cache-Control":"public, max-age=300","Access-Control-Allow-Origin":"*"}});
}
