"use client";
import { ChangeEvent,useRef,useState } from "react";
import { createCsv,parseCsv,type CsvColumn } from "@/lib/csv";

export default function CsvBulkActions({title,columns,rows,importUrl,canImport,onImported}:{title:string;columns:CsvColumn[];rows:Array<Record<string,unknown>>;importUrl:string;canImport:boolean;onImported:()=>Promise<void>}){
 const input=useRef<HTMLInputElement>(null),[guide,setGuide]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 function download(content:string,name:string){const blob=new Blob([`\uFEFF${content}`],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
 function exportRows(){download(createCsv(columns,rows),`${title.toLowerCase().replaceAll(" ","-")}.csv`);setMessage(`${rows.length} record${rows.length===1?"":"s"} exported.`)}
 function template(){download(createCsv(columns,[Object.fromEntries(columns.map(column=>[column.key,column.sample??""]))]),`${title.toLowerCase().replaceAll(" ","-")}-template.csv`)}
 async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);setMessage("");try{const parsed=parseCsv(await file.text()),allowed=new Set(columns.map(column=>column.key)),unknown=Object.keys(parsed[0]||{}).filter(key=>!allowed.has(key));if(unknown.length)throw new Error(`Unknown column${unknown.length===1?"":"s"}: ${unknown.join(", ")}`);const missing=columns.filter(column=>column.required&&!Object.keys(parsed[0]||{}).includes(column.key));if(missing.length)throw new Error(`Missing required column${missing.length===1?"":"s"}: ${missing.map(column=>column.key).join(", ")}`);const response=await fetch(importUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:parsed})}),payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error+(payload?.details?.row?` (row ${payload.details.row})`:"")||"Import failed");setMessage(`${payload.data.imported} records imported successfully.`);await onImported()}catch(cause){setMessage(cause instanceof Error?cause.message:"Unable to import CSV")}finally{setBusy(false)}}
 return <div className="rounded-xl border border-[#eee8da] bg-[#fffdf8] p-3"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={exportRows} className="min-h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-bold text-[#102039]">Export CSV</button>{canImport&&<><input ref={input} type="file" accept=".csv,text/csv" onChange={event=>void importFile(event)} className="sr-only"/><button type="button" disabled={busy} onClick={()=>input.current?.click()} className="min-h-10 rounded-lg bg-[#102039] px-3 text-xs font-bold text-white disabled:opacity-50">{busy?"Importing…":"Bulk import CSV"}</button></>}<button type="button" onClick={()=>setGuide(value=>!value)} aria-expanded={guide} className="min-h-10 rounded-lg px-3 text-xs font-bold text-[#9f6d00] underline">CSV import guide</button></div>{message&&<p role="status" className="mt-2 text-xs text-slate-600">{message}</p>}{guide&&<div className="mt-3 rounded-lg border border-amber-100 bg-white p-4 text-sm"><h3 className="font-extrabold">How to import {title.toLowerCase()}</h3><ol className="mt-2 list-decimal space-y-1 pl-5 text-slate-600"><li>Download the template and keep its header names unchanged.</li><li>Add one record per row. Save the file as UTF-8 CSV.</li><li>Required columns are marked below. Imports are all-or-nothing.</li><li>Upload at most 500 rows. Fix the reported row if validation fails.</li></ol><p className="mt-3 break-words rounded bg-slate-50 p-2 font-mono text-xs">{columns.map(column=>column.key).join(",")}</p><p className="mt-2 text-xs text-slate-500">Required: {columns.filter(column=>column.required).map(column=>column.key).join(", ")||"none"}</p><button type="button" onClick={template} className="mt-3 min-h-9 rounded-lg border border-amber-300 px-3 text-xs font-bold text-[#9f6d00]">Download CSV template</button></div>}</div>
}
