"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useLanguage } from "@/components/LanguageProvider";
import type { Language } from "@/lib/i18n";

type Profile = { displayName:string;phone:string;address:string;bio:string;avatarUrl:string;email:string;role:string;tenantId:string };
type Copy = { eyebrow:string;title:string;description:string;loading:string;displayName:string;phone:string;address:string;bio:string;avatarUrl:string;optional:string;save:string;saving:string;saved:string;security:string;securityHelp:string;email:string;role:string;school:string;locked:string };

const copy:Record<Language,Copy>={
  en:{eyebrow:"Account",title:"My profile",description:"Update the personal details people use to recognize and contact you.",loading:"Loading your profile…",displayName:"Display name",phone:"Phone",address:"Address",bio:"Short bio",avatarUrl:"Profile photo URL",optional:"Optional",save:"Save profile",saving:"Saving…",saved:"Profile updated successfully.",security:"Protected account details",securityHelp:"These fields control identity and access. Only an authorized administrator can change them.",email:"Sign-in email",role:"Role",school:"School tenant",locked:"Locked"},
  ar:{eyebrow:"الحساب",title:"ملفي الشخصي",description:"حدّث بياناتك الشخصية التي يستخدمها الآخرون للتعرّف عليك والتواصل معك.",loading:"جارٍ تحميل ملفك…",displayName:"اسم العرض",phone:"الهاتف",address:"العنوان",bio:"نبذة قصيرة",avatarUrl:"رابط صورة الملف",optional:"اختياري",save:"حفظ الملف",saving:"جارٍ الحفظ…",saved:"تم تحديث الملف بنجاح.",security:"بيانات الحساب المحمية",securityHelp:"تتحكم هذه الحقول في الهوية والصلاحيات، ولا يغيّرها إلا مسؤول مخوّل.",email:"بريد تسجيل الدخول",role:"الدور",school:"معرّف المدرسة",locked:"مقفل"},
  fr:{eyebrow:"Compte",title:"Mon profil",description:"Mettez à jour les informations personnelles utilisées pour vous identifier et vous contacter.",loading:"Chargement du profil…",displayName:"Nom affiché",phone:"Téléphone",address:"Adresse",bio:"Courte biographie",avatarUrl:"URL de la photo",optional:"Facultatif",save:"Enregistrer",saving:"Enregistrement…",saved:"Profil mis à jour.",security:"Informations de compte protégées",securityHelp:"Ces champs contrôlent l’identité et l’accès. Seul un administrateur autorisé peut les modifier.",email:"E-mail de connexion",role:"Rôle",school:"Établissement",locked:"Verrouillé"},
  bn:{eyebrow:"অ্যাকাউন্ট",title:"আমার প্রোফাইল",description:"অন্যরা আপনাকে চিনতে ও যোগাযোগ করতে যে ব্যক্তিগত তথ্য ব্যবহার করে তা হালনাগাদ করুন।",loading:"প্রোফাইল লোড হচ্ছে…",displayName:"প্রদর্শিত নাম",phone:"ফোন",address:"ঠিকানা",bio:"সংক্ষিপ্ত পরিচিতি",avatarUrl:"প্রোফাইল ছবির URL",optional:"ঐচ্ছিক",save:"প্রোফাইল সংরক্ষণ",saving:"সংরক্ষণ হচ্ছে…",saved:"প্রোফাইল সফলভাবে হালনাগাদ হয়েছে।",security:"সুরক্ষিত অ্যাকাউন্ট তথ্য",securityHelp:"এই তথ্য পরিচয় ও প্রবেশাধিকার নিয়ন্ত্রণ করে। শুধু অনুমোদিত প্রশাসক এগুলো পরিবর্তন করতে পারেন।",email:"সাইন-ইন ইমেইল",role:"ভূমিকা",school:"স্কুল টেন্যান্ট",locked:"লক করা"},
  es:{eyebrow:"Cuenta",title:"Mi perfil",description:"Actualiza los datos personales que otros usan para reconocerte y contactarte.",loading:"Cargando tu perfil…",displayName:"Nombre visible",phone:"Teléfono",address:"Dirección",bio:"Biografía breve",avatarUrl:"URL de foto de perfil",optional:"Opcional",save:"Guardar perfil",saving:"Guardando…",saved:"Perfil actualizado correctamente.",security:"Datos de cuenta protegidos",securityHelp:"Estos campos controlan la identidad y el acceso. Solo un administrador autorizado puede cambiarlos.",email:"Correo de acceso",role:"Rol",school:"Escuela",locked:"Bloqueado"},
};

const blank:Profile={displayName:"",phone:"",address:"",bio:"",avatarUrl:"",email:"",role:"",tenantId:""};

export default function EditableProfile({fallback}:{fallback:Pick<Profile,"displayName"|"email"|"role"|"tenantId">}){
  const {language}=useLanguage(),labels=copy[language],router=useRouter();
  const [profile,setProfile]=useState<Profile>({...blank,...fallback});
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{let active=true;void fetch("/api/profile",{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load profile");if(active)setProfile(payload.data)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load profile")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const initials=useMemo(()=>profile.displayName.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase()||"U",[profile.displayName]);
  const update=(key:keyof Profile,value:string)=>setProfile(current=>({...current,[key]:value}));
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:profile.displayName,phone:profile.phone,address:profile.address,bio:profile.bio,avatarUrl:profile.avatarUrl})}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to update profile");setProfile(payload.data);setNotice(labels.saved);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to update profile")}finally{setSaving(false)}}
  const input="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-amber-400 focus:ring-2 focus:ring-amber-100";
  return <div className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#c88700]">{labels.eyebrow}</p><h1 className="mt-1 text-2xl font-extrabold text-[#102039]">{labels.title}</h1><p className="mt-1 text-sm text-slate-500">{labels.description}</p></header>
    <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><form onSubmit={save} className="rounded-2xl border border-[#efede7] bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-full border-4 border-amber-200 bg-amber-50 text-2xl font-black text-amber-800">{profile.avatarUrl?<img src={profile.avatarUrl} alt="" className="h-full w-full object-cover" referrerPolicy="no-referrer" onError={event=>{event.currentTarget.style.display="none"}}/>:initials}</div><div className="min-w-0"><h2 className="truncate text-lg font-extrabold text-[#102039]">{profile.displayName||fallback.displayName}</h2><p className="truncate text-sm capitalize text-slate-500">{profile.role}</p></div></div>
      {loading?<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">{labels.loading}</p>:<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">{labels.displayName}<input required minLength={2} maxLength={80} value={profile.displayName} onChange={event=>update("displayName",event.target.value)} className={input}/></label><label className="text-sm font-semibold text-slate-700">{labels.phone} <span className="font-normal text-slate-400">({labels.optional})</span><input type="tel" maxLength={30} value={profile.phone} onChange={event=>update("phone",event.target.value)} className={input}/></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">{labels.address} <span className="font-normal text-slate-400">({labels.optional})</span><input maxLength={160} value={profile.address} onChange={event=>update("address",event.target.value)} className={input}/></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">{labels.bio} <span className="font-normal text-slate-400">({labels.optional})</span><textarea maxLength={300} rows={4} value={profile.bio} onChange={event=>update("bio",event.target.value)} className={input}/></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">{labels.avatarUrl} <span className="font-normal text-slate-400">({labels.optional})</span><input type="url" maxLength={500} placeholder="https://…" value={profile.avatarUrl} onChange={event=>update("avatarUrl",event.target.value)} className={input}/></label></div>}
      {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<div className="mt-6 flex justify-end"><button disabled={loading||saving} className="min-h-11 rounded-xl bg-[#e7a000] px-6 text-sm font-bold text-white transition hover:bg-[#ca8c00] disabled:cursor-not-allowed disabled:opacity-50">{saving?labels.saving:labels.save}</button></div></form>
      <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-7"><div className="flex items-start gap-3"><span aria-hidden="true" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-900 text-white">🔒</span><div><h2 className="font-extrabold text-[#102039]">{labels.security}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{labels.securityHelp}</p></div></div><dl className="mt-6 space-y-3">{[[labels.email,profile.email],[labels.role,profile.role],[labels.school,profile.tenantId]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="flex items-center justify-between gap-3 text-[10px] font-bold uppercase tracking-wider text-slate-400"><span>{label}</span><span>{labels.locked}</span></dt><dd className="mt-1 break-all text-sm font-bold capitalize text-[#27364b]">{value||"—"}</dd></div>)}</dl></aside></div></div>;
}
