"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { FormEvent, KeyboardEvent, useEffect, useId, useRef, useState } from "react";
import { useLanguage } from "@/components/LanguageProvider";

type Result={id:string;title:string;subtitle:string;category:string;href:string;icon:string};
export default function GlobalSearch(){
  const router=useRouter(),listId=useId(),root=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
  const {t}=useLanguage();
  const [query,setQuery]=useState(""),[results,setResults]=useState<Result[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[active,setActive]=useState(-1);
  useEffect(()=>{const shortcut=(event:KeyboardEvent|globalThis.KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();input.current?.focus();setOpen(true)}};const outside=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};window.addEventListener("keydown",shortcut as EventListener);document.addEventListener("mousedown",outside);return()=>{window.removeEventListener("keydown",shortcut as EventListener);document.removeEventListener("mousedown",outside)}},[]);
  useEffect(()=>{if(query.trim().length<2){setResults([]);setLoading(false);return}const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);void fetch(`/api/search?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal}).then(async response=>{const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error||"Search unavailable");setResults(payload.data||[]);setActive((payload.data||[]).length?0:-1);setOpen(true)}).catch(error=>{if(error instanceof Error&&error.name!=="AbortError")setResults([])}).finally(()=>setLoading(false))},180);return()=>{window.clearTimeout(timer);controller.abort()}},[query]);
  function go(result?:Result){const target=result||results[active]||results[0];if(!target)return;setOpen(false);setQuery("");router.push(target.href)}
  function keys(event:KeyboardEvent<HTMLInputElement>){if(event.key==="ArrowDown"){event.preventDefault();setOpen(true);setActive(value=>Math.min(results.length-1,value+1))}else if(event.key==="ArrowUp"){event.preventDefault();setActive(value=>Math.max(0,value-1))}else if(event.key==="Enter"&&open){event.preventDefault();go()}else if(event.key==="Escape"){setOpen(false);event.currentTarget.blur()}}
  function submit(event:FormEvent){event.preventDefault();go()}
  return <div ref={root} className="relative w-full max-w-[440px]"><form role="search" onSubmit={submit}><label htmlFor="global-search" className="sr-only">{t("searchSystem")}</label><div className={`flex h-12 items-center rounded-xl border bg-[#fbfbfb] px-4 transition-all duration-200 ${open?"border-[#e9aa00] shadow-[0_8px_28px_rgba(210,143,0,.12)]":"border-slate-200 hover:border-slate-300"}`}><input ref={input} id="global-search" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={listId} aria-activedescendant={active>=0?`${listId}-${active}`:undefined} value={query} onFocus={()=>query.length>=2&&setOpen(true)} onChange={event=>setQuery(event.target.value)} onKeyDown={keys} placeholder={t("searchPlaceholder")} className="min-w-0 flex-1 bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400"/><span className="ms-3 flex items-center gap-2"><kbd className="hidden rounded border bg-white px-1.5 py-0.5 text-[9px] font-semibold text-slate-400 xl:inline">⌘ K</kbd><Image src="/search.png" alt="" width={19} height={19} className={loading?"animate-pulse opacity-40":"opacity-55"}/></span></div></form>{open&&<div id={listId} role="listbox" aria-label={t("searchResults")} className="absolute inset-x-0 top-[calc(100%+.55rem)] z-50 max-h-[min(440px,70vh)] overflow-y-auto rounded-2xl border border-slate-100 bg-white p-2 shadow-[0_24px_70px_rgba(15,23,42,.18)]">{query.length<2?<p className="p-4 text-sm text-slate-500">{t("typeTwo")}</p>:loading&&!results.length?<p className="p-4 text-sm text-slate-500">{t("searching")}</p>:results.length?results.map((result,index)=><button type="button" id={`${listId}-${index}`} role="option" aria-selected={index===active} key={result.id} onMouseEnter={()=>setActive(index)} onClick={()=>go(result)} className={`flex min-h-[58px] w-full items-center gap-3 rounded-xl px-3 py-2 text-start transition ${index===active?"bg-[#fff7e5]":"hover:bg-slate-50"}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-amber-100 bg-white"><Image src={result.icon} alt="" width={18} height={18}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#102039]">{result.title}</strong><span className="block truncate text-xs text-slate-500">{result.subtitle}</span></span><span className="shrink-0 text-[10px] font-bold uppercase tracking-wider text-[#b77c00]">{result.category}</span></button>):<p role="status" className="p-5 text-center text-sm text-slate-500">{t("noResults")}</p>}<div className="sticky bottom-0 mt-1 flex justify-between border-t bg-white px-3 py-2 text-[10px] text-slate-400"><span>↑↓ {t("navigateOpen")}</span><span>{t("escClose")}</span></div></div>}</div>
}
