"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { useLanguage } from "@/components/LanguageProvider";

export default function PlatformSignInForm(){
  const router=useRouter();const [email,setEmail]=useState("superadmin@sime.local"),[password,setPassword]=useState("SuperAdmin123!"),[error,setError]=useState(""),[loading,setLoading]=useState(false),[showPassword,setShowPassword]=useState(false);
  const {t}=useLanguage();
  async function submit(event:FormEvent){event.preventDefault();if(loading)return;setLoading(true);setError("");try{const response=await fetch("/api/platform/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error||"Platform sign in failed");router.replace("/superadmin");router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to connect to the platform server");setLoading(false)}}
  return <main id="main-content" className="min-h-screen bg-[#071827] text-white"><div className="grid min-h-screen lg:grid-cols-[1fr_.9fr]"><form onSubmit={submit} aria-describedby={error?"platform-login-error":undefined} aria-busy={loading} className="relative flex flex-col justify-center px-7 py-10 sm:px-16 lg:px-[14%]"><div className="absolute end-6 top-6"><LanguageSwitcher dark/></div><Image src="/design/brand-logo.png" alt="SIME" width={140} height={54} priority className="mb-16 h-12 w-auto self-start rounded bg-white object-contain px-2"/><p className="text-xs font-bold uppercase tracking-[.22em] text-[#efa900]">{t("restrictedAccess")}</p><h1 className="mt-3 text-3xl font-black">{t("superadminSignIn")}</h1><p className="mt-2 max-w-lg text-sm leading-6 text-slate-300">{t("platformDescription")}</p><div className="mt-8 space-y-5"><label className="block text-xs font-semibold text-slate-300">{t("platformEmail")}<input required type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} className="mt-2 w-full rounded-lg border border-white/20 bg-white/10 px-4 py-3 text-sm text-white placeholder:text-slate-500" dir="ltr"/></label><label className="block text-xs font-semibold text-slate-300">{t("password")}<span className="relative mt-2 block"><input required type={showPassword?"text":"password"} autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} className="w-full rounded-lg border border-white/20 bg-white/10 py-3 ps-4 pe-16 text-sm text-white"/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?t("hide"):t("show")} className="absolute inset-y-0 end-1 my-auto min-h-10 rounded-md px-3 text-xs font-bold text-slate-200 hover:bg-white/10">{showPassword?t("hide"):t("show")}</button></span></label></div>{error&&<p id="platform-login-error" role="alert" aria-live="assertive" className="mt-4 rounded-lg bg-red-950/60 p-3 text-sm text-red-200">{error}</p>}<button disabled={loading} className="mt-7 min-h-11 w-full rounded-lg bg-[#efa900] py-3 text-sm font-black text-[#071827] disabled:opacity-50">{loading?t("signingIn"):t("enterPlatform")}</button><Link href="/sign-in" className="mt-5 min-h-11 text-center text-sm font-semibold text-slate-300 hover:text-white">← {t("returnSchool")}</Link></form><section aria-label="Platform security summary" className="hidden items-center justify-center bg-gradient-to-br from-[#123550] to-[#0c2237] p-12 lg:flex"><div className="max-w-md"><p className="text-6xl font-black text-[#efa900]">SIME</p><h2 className="mt-5 text-3xl font-black">One platform.<br/>Isolated schools.</h2><div className="mt-8 space-y-4 text-sm text-slate-300">{["Separate platform and school authentication","Tenant-scoped database access","Immediate session revocation for suspended schools"].map(item=><p key={item} className="rounded-xl border border-white/10 bg-white/5 p-4">✓ {item}</p>)}</div></div></section></div></main>;
}
