import { z } from "zod";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { assignmentAvailableToStudent, parentStudentNames, submissionSelect } from "@/lib/assignment-submissions";
import { getClientIp, jsonError, rateLimit } from "@/lib/http";
import { securityOriginValid } from "@/lib/security";
const link=z.string().trim().max(1000).refine(value=>!value||/^https?:\/\//i.test(value),"Attachment must be an HTTP(S) link");
const schema=z.object({assignmentId:z.coerce.number().int().positive(),content:z.string().trim().max(10000).default(""),attachmentUrl:link.default(""),status:z.enum(["draft","submitted"]).default("draft")}).refine(value=>value.status!=="submitted"||Boolean(value.content||value.attachmentUrl),{message:"Add an answer or attachment before submitting"});
export async function GET(request:Request){const session=await getSession();if(!session)return jsonError("Authentication required",401);const raw=new URL(request.url).searchParams.get("assignmentId"),assignmentId=raw?z.coerce.number().int().positive().safeParse(raw):null;if(assignmentId&&!assignmentId.success)return jsonError("Invalid assignment",400);const filters=["s.tenant_id=?"],values:Array<string|number>=[session.tenantId];if(assignmentId?.success){filters.push("s.assignment_id=?");values.push(assignmentId.data)}if(session.role==="student"){filters.push("s.student_email=?");values.push(session.userId)}else if(session.role==="parent"){const children=parentStudentNames(session);if(!children.length)return Response.json({data:[]});filters.push(`s.student_name IN (${children.map(()=>"?").join(",")})`);values.push(...children)}else if(session.role!=="admin"&&session.role!=="teacher")return jsonError("Submission access denied",403);const rows=db.prepare(`${submissionSelect} WHERE ${filters.join(" AND ")} ORDER BY s.updated_at DESC LIMIT 200`).all(...values);return Response.json({data:rows},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:Request){const session=await getSession();if(!session)return jsonError("Authentication required",401);if(session.role!=="student")return jsonError("Only students can submit their assignment work",403);if(!securityOriginValid(request,session.tenantId))return jsonError("Invalid request origin",403);const limit=rateLimit(`assignment-submit:${session.tenantId}:${getClientIp(request)}:${session.userId}`,30);if(!limit.allowed)return jsonError("Too many submission requests",429,{retryAfter:limit.retryAfter});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return jsonError("Invalid assignment submission",400,parsed.error.flatten());if(!assignmentAvailableToStudent(session,parsed.data.assignmentId))return jsonError("This assignment is not available to your class",403);try{const data=parsed.data,result=db.prepare("INSERT INTO assignment_submissions (tenant_id,assignment_id,student_email,student_name,content,attachment_url,status,submitted_at) VALUES (?,?,?,?,?,?,?,CASE WHEN ?='submitted' THEN CURRENT_TIMESTAMP ELSE NULL END)").run(session.tenantId,data.assignmentId,session.userId,session.name,data.content,data.attachmentUrl,data.status,data.status);const row=db.prepare(`${submissionSelect} WHERE s.id=? AND s.tenant_id=?`).get(result.lastInsertRowid,session.tenantId);return Response.json({data:row},{status:201})}catch(error){if(error instanceof Error&&error.message.includes("UNIQUE"))return jsonError("You already have a submission for this assignment. Open it to edit or submit it.",409);return jsonError("Unable to save assignment submission",500)}}
