import nextEnv from "@next/env";
import { AsyncLocalStorage } from "node:async_hooks";
import { createRequire } from "node:module";
nextEnv.loadEnvConfig(process.cwd());
process.env.OPENROUTER_API_KEY="verification-key";
globalThis.AsyncLocalStorage=AsyncLocalStorage;
const require=createRequire(import.meta.url),{NextRequest}=require("next/server"),Database=require("better-sqlite3");
const ai=require("../.next/server/app/api/ai/route.js"),history=require("../.next/server/app/api/ai/conversations/route.js"),conversation=require("../.next/server/app/api/ai/conversations/[id]/route.js"),models=require("../.next/server/app/api/ai/models/route.js"),login=require("../.next/server/app/api/auth/login/route.js");
const base="http://127.0.0.1:6969",failures=[],createdConversationIds=[];let checks=0,capturedSystems=[];
function check(value,label,detail=""){checks++;if(!value)failures.push(`${label}${detail?`: ${detail}`:""}`)}
function context(params){return {params,prerenderManifest:{preview:{previewModeId:"",previewModeSigningKey:"",previewModeEncryptionKey:""}},renderOpts:{supportsDynamicResponse:true,experimental:{authInterrupts:false},cacheComponents:false,waitUntil:()=>{},onClose:()=>{},onAfterTaskError:undefined,onInstrumentationRequestError:()=>{}},sharedContext:{buildId:"ai-verification"}}}
async function signIn(email,password){const response=await login.routeModule.userland.POST(new Request(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json",origin:base},body:JSON.stringify({tenantId:"demo-school",email,password})}));check(response.status===200,`${email} login`);return (response.headers.get("set-cookie")||"").split(";")[0]}
async function handle(module,path,cookie,method="GET",body,params){return module.routeModule.handle(new NextRequest(`${base}${path}`,{method,headers:{cookie,...(body?{"content-type":"application/json",origin:base}:{})},body:body?JSON.stringify(body):undefined}),context(params))}
function tool(name,args){return new Response(JSON.stringify({choices:[{message:{content:null,tool_calls:[{id:"verify-tool",type:"function",function:{name,arguments:JSON.stringify(args)}}]}}]}),{headers:{"content-type":"application/json"}})}
const realFetch=globalThis.fetch;
globalThis.fetch=async(input,init)=>{const url=String(input);if(!url.startsWith("https://openrouter.ai/"))return realFetch(input,init);if(url.endsWith("/models"))return new Response(JSON.stringify({data:[{id:"openrouter/free",name:"OpenRouter Free",context_length:100000,pricing:{prompt:"0",completion:"0"}},{id:"example/paid",name:"Example Paid",context_length:32000,pricing:{prompt:"0.001",completion:"0.002"}}]}),{headers:{"content-type":"application/json"}});const body=JSON.parse(String(init?.body||"{}")),messages=body.messages||[];capturedSystems.push(String(messages[0]?.content||""));if(messages.some(message=>message.role==="tool"))return new Response(JSON.stringify({choices:[{message:{content:"The authorized action finished and is recorded in the audit log."}}]}),{headers:{"content-type":"application/json"}});const prompt=String(messages.at(-1)?.content||"");if(prompt.includes("FORCE-OFFLINE"))throw new Error("simulated provider outage");if(prompt.includes("DELETE-CONVERSATION-DURING")){const row=database.prepare("SELECT conversation_id conversationId FROM ai_messages WHERE content=? ORDER BY id DESC LIMIT 1").get(prompt);if(row)database.prepare("DELETE FROM ai_conversations WHERE id=?").run(row.conversationId)}if(prompt.includes("AI-VERIFY-STUDENT"))return tool("create_student",{studentId:"AI-VERIFY-STUDENT",name:"AI Verify Student",email:"ai-verify@example.edu",phone:"",grade:8,className:"8-A",address:"Dhaka",gender:"female"});if(prompt.includes("MALICIOUS-STUDENT"))return tool("create_student",{studentId:"MALICIOUS-STUDENT",name:"Denied Student",email:"denied@example.edu",grade:7,className:"7-A"});if(prompt.includes("AI verification announcement"))return tool("create_announcements",{title:"AI verification announcement",class:"All",date:"2026-07-23"});return new Response(JSON.stringify({choices:[{message:{content:"I reviewed the authorized live school context."}}]}),{headers:{"content-type":"application/json"}})};

const database=new Database(process.env.DATABASE_PATH||"./data/sime.db");
try{
 const admin=await signIn("admin@sime.local","ChangeMe123!"),teacher=await signIn("teacher@sime.local","Teacher123!"),student=await signIn("student@sime.local","Student123!"),parent=await signIn("parent@sime.local","Parent123!");
 const anonymous=await handle(history,"/api/ai/conversations","", "GET");check(anonymous.status===401,"anonymous history denied");
 const created=await handle(ai,"/api/ai",admin,"POST",{message:"Create student AI-VERIFY-STUDENT with the supplied details"});const createdData=(await created.json()).data;createdConversationIds.push(createdData?.conversationId);check(created.status===200&&createdData.actions?.[0]?.ok,"admin AI creates student");check(Boolean(database.prepare("SELECT 1 FROM students WHERE tenant_id=? AND student_id=?").get("demo-school","AI-VERIFY-STUDENT")),"AI student persisted");
 const adminHistory=await handle(history,"/api/ai/conversations",admin);const adminRows=(await adminHistory.json()).data;check(adminRows.some(row=>row.id===createdData.conversationId),"admin conversation saved");
 const parentRead=await handle(conversation,`/api/ai/conversations/${createdData.conversationId}`,parent,"GET",undefined,{id:createdData.conversationId});check(parentRead.status===404,"conversation owner isolation");
 const denied=await handle(ai,"/api/ai",student,"POST",{message:"Create MALICIOUS-STUDENT now"});const deniedData=(await denied.json()).data;createdConversationIds.push(deniedData?.conversationId);check(denied.status===200&&!deniedData.actions[0].ok,"student AI action denied");check(!database.prepare("SELECT 1 FROM students WHERE student_id='MALICIOUS-STUDENT'").get(),"denied student not persisted");
 const teacherCreate=await handle(ai,"/api/ai",teacher,"POST",{message:"Create AI verification announcement"});const teacherJson=await teacherCreate.json(),teacherData=teacherJson.data;createdConversationIds.push(teacherData?.conversationId);check(teacherCreate.status===200&&teacherData?.actions?.[0]?.ok,"teacher permitted AI record creation",`${teacherCreate.status} ${JSON.stringify(teacherJson)}`);
 const studentAnswer=await handle(ai,"/api/ai",student,"POST",{message:"Review my authorized school information"});const studentAnswerData=(await studentAnswer.json()).data;createdConversationIds.push(studentAnswerData?.conversationId);check(studentAnswer.status===200,"student database-aware answer");const studentSystem=capturedSystems.at(-1)||"";check(studentSystem.includes("Jessica Rose")&&!studentSystem.includes("Nabil Hasan"),"student context record isolation");check(!studentSystem.includes("teacher@sime.local"),"student context teacher PII redaction");
 const offline=await handle(ai,"/api/ai",admin,"POST",{message:"FORCE-OFFLINE summarize assignments"});const offlineJson=await offline.json(),offlineData=offlineJson.data;createdConversationIds.push(offlineData?.conversationId);check(offline.status===200&&offlineData?.degraded===true&&offlineData?.answer?.toLowerCase().includes("assignment"),"AI provider outage uses database fallback",`${offline.status} ${JSON.stringify(offlineJson)}`);
 const recovered=await handle(ai,"/api/ai",admin,"POST",{message:"DELETE-CONVERSATION-DURING verify recovery"});const recoveredJson=await recovered.json(),recoveredData=recoveredJson.data;createdConversationIds.push(recoveredData?.conversationId);const recoveredMessages=database.prepare("SELECT COUNT(*) count FROM ai_messages WHERE conversation_id=?").get(recoveredData?.conversationId);check(recovered.status===200&&recoveredData?.conversationId&&recoveredMessages?.count===2,"AI recovers conversation deleted while response is in flight",`${recovered.status} ${JSON.stringify(recoveredJson)}`);
 const modelList=await handle(models,"/api/ai/models",admin);const modelData=(await modelList.json()).data;check(modelList.status===200&&modelData.connected&&modelData.models.length===2&&modelData.models[0].free,"admin model discovery and status");const modelDenied=await handle(models,"/api/ai/models",student);check(modelDenied.status===403,"model discovery admin-only");
 const fullConversation=await handle(conversation,`/api/ai/conversations/${createdData.conversationId}`,admin,"GET",undefined,{id:createdData.conversationId});const fullData=(await fullConversation.json()).data;check(fullConversation.status===200&&fullData.messages.length===2,"saved message history loaded");
 const removed=await handle(conversation,`/api/ai/conversations/${createdData.conversationId}`,admin,"DELETE",undefined,{id:createdData.conversationId});check(removed.status===204,"conversation clear/delete");
}finally{
 database.prepare("DELETE FROM students WHERE tenant_id='demo-school' AND student_id IN ('AI-VERIFY-STUDENT','MALICIOUS-STUDENT')").run();database.prepare("DELETE FROM resources WHERE tenant_id='demo-school' AND resource_type='announcements' AND title='AI verification announcement'").run();for(const id of createdConversationIds.filter(Boolean)){database.prepare("DELETE FROM ai_action_audit WHERE conversation_id=?").run(id);database.prepare("DELETE FROM ai_conversations WHERE id=?").run(id)}database.close();globalThis.fetch=realFetch;
}
if(failures.length){console.error(`FAILED ${failures.length}/${checks}\n${failures.join("\n")}`);process.exit(1)}console.log(`PASS ${checks} AI checks for persistence, live context, model discovery, RBAC, tenant/user isolation, actions, and clearing history.`);
