-- User-authorized replacement of the disposable CRM schema with SIME.
-- Core Supabase schemas (auth, storage, realtime, extensions) are not dropped.

drop schema if exists public cascade;
create schema public;
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;

create extension if not exists pgcrypto with schema extensions;

create table public.tenants (
  id text primary key,
  name text not null,
  active boolean not null default true,
  plan text not null default 'starter',
  license_status text not null default 'trial' check (license_status in ('trial','active','expired','suspended')),
  license_starts_at timestamptz not null default now(),
  license_expires_at timestamptz,
  max_students integer not null default 500 check (max_students between 1 and 1000000),
  max_users integer not null default 100 check (max_users between 1 and 100000),
  contact_email text not null default '',
  created_at timestamptz not null default now()
);

create table public.schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

create table public.users (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  email text not null,
  name text not null,
  role text not null check (role in ('superadmin','admin','teacher','student','parent')),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id,email)
);

create table public.security_settings (
  tenant_id text primary key references public.tenants(id) on delete cascade,
  max_login_attempts integer not null default 5 check (max_login_attempts between 3 and 20),
  lockout_minutes integer not null default 15 check (lockout_minutes between 1 and 1440),
  session_hours integer not null default 8 check (session_hours between 1 and 168),
  ai_requests_per_minute integer not null default 10 check (ai_requests_per_minute between 1 and 100),
  require_strong_passwords boolean not null default true,
  enforce_same_origin boolean not null default true,
  secure_cookies boolean not null default true,
  audit_logging boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.login_attempts (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  email text not null,
  ip text not null,
  success boolean not null,
  created_at timestamptz not null default now()
);
create index idx_login_attempts_lookup on public.login_attempts(tenant_id,email,ip,created_at desc);

create table public.students (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  student_id text not null,
  name text not null,
  email text not null,
  phone text not null default '',
  grade integer not null check (grade between 1 and 12),
  class_name text not null,
  address text not null default '',
  gender text not null default 'unspecified' check (gender in ('female','male','other','unspecified')),
  blood_type text not null default 'Unknown',
  photo_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id,student_id),
  unique (tenant_id,email)
);
create index idx_students_tenant_name on public.students(tenant_id,name);

create table public.resources (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  resource_type text not null,
  title text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_resources_tenant_type on public.resources(tenant_id,resource_type,updated_at desc);

create table public.assignment_submissions (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  assignment_id bigint not null references public.resources(id) on delete cascade,
  student_email text not null,
  student_name text not null,
  content text not null default '',
  attachment_url text not null default '',
  status text not null default 'draft' check (status in ('draft','submitted','reviewed','returned')),
  score double precision,
  feedback text not null default '',
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id,assignment_id,student_email)
);
create index idx_assignment_submissions_lookup on public.assignment_submissions(tenant_id,assignment_id,status,updated_at desc);
create index idx_assignment_submissions_assignment on public.assignment_submissions(assignment_id);

create table public.ai_audit (
  id bigint generated by default as identity primary key,
  tenant_id text not null default 'demo-school',
  request_id text not null unique,
  model text not null,
  prompt_chars integer not null,
  status text not null,
  created_at timestamptz not null default now()
);
create index idx_ai_audit_tenant_created on public.ai_audit(tenant_id,created_at desc);

create table public.ai_settings (
  tenant_id text primary key references public.tenants(id) on delete cascade,
  api_key_encrypted text not null default '',
  model text not null default 'openrouter/free',
  enabled boolean not null default true,
  floating_enabled boolean not null default true,
  allow_admin boolean not null default true,
  allow_teacher boolean not null default true,
  allow_student boolean not null default true,
  allow_parent boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.ai_conversations (
  id text primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  user_email text not null,
  title text not null default 'New conversation',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_ai_conversations_owner on public.ai_conversations(tenant_id,user_email,updated_at desc);

create table public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.ai_conversations(id) on delete cascade,
  tenant_id text not null references public.tenants(id) on delete cascade,
  user_email text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  model text not null default '',
  action_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index idx_ai_messages_conversation on public.ai_messages(conversation_id,id);
create index idx_ai_messages_tenant on public.ai_messages(tenant_id);

create table public.ai_action_audit (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  user_email text not null,
  conversation_id text not null,
  action text not null,
  target_type text not null,
  target_id text not null default '',
  arguments_json jsonb not null default '{}'::jsonb,
  status text not null check (status in ('success','denied','error')),
  created_at timestamptz not null default now()
);
create index idx_ai_actions_tenant_created on public.ai_action_audit(tenant_id,created_at desc);

create table public.gamification_settings (
  tenant_id text primary key references public.tenants(id) on delete cascade,
  enabled boolean not null default true,
  attendance_points integer not null default 10 check (attendance_points between 0 and 500),
  assignment_points integer not null default 20 check (assignment_points between 0 and 500),
  exam_points integer not null default 30 check (exam_points between 0 and 500),
  behavior_points integer not null default 15 check (behavior_points between 0 and 500),
  global_leaderboard_public boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.gamification_points (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  points integer not null check (points between -1000 and 1000),
  source text not null check (source in ('attendance','assignment','exam','behavior','bonus')),
  note text not null default '',
  awarded_by text not null,
  created_at timestamptz not null default now()
);
create index idx_gamification_leaderboard on public.gamification_points(tenant_id,class_name,student_name);

create table public.intervention_notes (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  author_email text not null,
  risk_status text not null check (risk_status in ('on_track','at_risk','high_risk')),
  note text not null,
  follow_up_at timestamptz,
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_intervention_notes_student on public.intervention_notes(tenant_id,student_id,created_at desc);
create index idx_intervention_notes_student_id on public.intervention_notes(student_id);

create table public.platform_audit (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  action text not null,
  tenant_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index idx_platform_audit_created on public.platform_audit(created_at desc);

create table public.notifications (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  audience_role text not null default 'all',
  user_email text not null default '',
  category text not null default 'system',
  title text not null,
  message text not null,
  link text not null default '',
  created_at timestamptz not null default now()
);
create index idx_notifications_audience on public.notifications(tenant_id,created_at desc,id desc);

create table public.notification_reads (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  tenant_id text not null,
  user_email text not null,
  read_at timestamptz not null default now(),
  primary key(notification_id,tenant_id,user_email)
);

create table public.platform_settings (
  id integer primary key default 1 check (id=1),
  platform_name text not null default 'SIME',
  support_email text not null default 'support@sime.local',
  default_plan text not null default 'starter',
  trial_days integer not null default 30 check (trial_days between 1 and 365),
  maintenance_mode boolean not null default false,
  allow_new_schools boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.developer_api_settings (
  tenant_id text primary key references public.tenants(id) on delete cascade,
  enabled boolean not null default false,
  school_visible boolean not null default false,
  allow_read boolean not null default true,
  allow_write boolean not null default false,
  requests_per_minute integer not null default 60 check (requests_per_minute between 10 and 1000),
  updated_at timestamptz not null default now()
);

create table public.developer_api_keys (
  id text primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  name text not null,
  key_prefix text not null,
  key_hash text not null unique,
  scopes jsonb not null default '["read"]'::jsonb,
  active boolean not null default true,
  expires_at timestamptz,
  last_used_at timestamptz,
  created_by text not null,
  created_at timestamptz not null default now()
);
create index idx_developer_keys_tenant on public.developer_api_keys(tenant_id,active,created_at desc);

create table public.developer_api_logs (
  id bigint generated by default as identity primary key,
  key_id text not null,
  tenant_id text not null,
  method text not null,
  path text not null,
  status integer not null,
  ip text not null default '',
  created_at timestamptz not null default now()
);
create index idx_developer_logs_tenant on public.developer_api_logs(tenant_id,created_at desc);

create or replace function public.sime_touch_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['students','resources','assignment_submissions','ai_settings','ai_conversations','gamification_settings','intervention_notes','platform_settings','developer_api_settings'] loop
    execute format('create trigger %I_touch before update on public.%I for each row execute function public.sime_touch_updated_at()',table_name,table_name);
  end loop;
end $$;

create or replace function public.sime_change_notification()
returns trigger language plpgsql security invoker set search_path = public as $$
declare row_data jsonb := case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
declare tenant text := coalesce(row_data->>'tenant_id','platform');
declare label text := replace(tg_table_name,'_',' ');
begin
  if tg_table_name <> 'notifications' then
    insert into public.notifications(tenant_id,audience_role,category,title,message,link)
    values(tenant,'all','system',initcap(label)||' '||lower(tg_op),initcap(label)||' changed and is available now.','');
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['students','resources','assignment_submissions','gamification_points','intervention_notes','security_settings','ai_settings','gamification_settings','developer_api_settings'] loop
    execute format('create trigger %I_notify after insert or update or delete on public.%I for each row execute function public.sime_change_notification()',table_name,table_name);
  end loop;
end $$;

-- All application access is server-side. Browser roles are explicitly denied.
do $$
declare item record;
begin
  for item in select tablename from pg_tables where schemaname='public' loop
    execute format('alter table public.%I enable row level security',item.tablename);
    execute format('create policy server_only on public.%I for all to anon, authenticated using (false) with check (false)',item.tablename);
  end loop;
end $$;

grant select,insert,update,delete on all tables in schema public to service_role;
grant usage,select on all sequences in schema public to service_role;
alter default privileges in schema public grant select,insert,update,delete on tables to service_role;
alter default privileges in schema public grant usage,select on sequences to service_role;

insert into public.platform_settings(id) values(1);
insert into public.schema_migrations(version) values('sime-postgres-v1');

-- Publish live application changes. Notifications drive the application SSE bridge;
-- the remaining tables support future direct Supabase Realtime clients.
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.resources;
alter publication supabase_realtime add table public.students;
alter publication supabase_realtime add table public.assignment_submissions;
alter publication supabase_realtime add table public.gamification_points;
alter publication supabase_realtime add table public.intervention_notes;
