-- Durable, tenant-safe academic-year domain for School-InG.
-- Direct Data API access remains denied: application servers use privileged,
-- audited adapters and never trust tenant identifiers from request bodies.

create unique index if not exists uq_students_tenant_row
  on public.students (tenant_id, id);

create table if not exists public.academic_years (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants(id) on delete cascade,
  name text not null check (char_length(name) between 3 and 40),
  code text not null check (char_length(code) between 3 and 20),
  country text not null default 'Guinea',
  timezone text not null default 'Africa/Conakry',
  default_language text not null default 'fr' check (default_language in ('en','ar','fr','es')),
  currency text not null default 'GNF',
  start_date date not null,
  end_date date not null,
  enrollment_start date not null,
  enrollment_end date not null,
  period_system text not null default 'terms' check (period_system in ('terms','semesters')),
  status text not null default 'draft' check (status in ('draft','scheduled','active','closed','archived')),
  school_opening_date date not null,
  holidays_json jsonb not null default '[]'::jsonb check (jsonb_typeof(holidays_json) = 'array'),
  closures_json jsonb not null default '[]'::jsonb check (jsonb_typeof(closures_json) = 'array'),
  exams_json jsonb not null default '[]'::jsonb check (jsonb_typeof(exams_json) = 'array'),
  grading_json jsonb not null default '{"maximum":20,"passMark":10}'::jsonb check (jsonb_typeof(grading_json) = 'object'),
  coefficients_json jsonb not null default '{}'::jsonb check (jsonb_typeof(coefficients_json) = 'object'),
  rounding_rule text not null default '0.01' check (rounding_rule in ('0.01','0.1','1')),
  ranking_rule text not null default 'dense' check (ranking_rule in ('dense','competition')),
  promotion_json jsonb not null default '{"minimumAverage":10}'::jsonb check (jsonb_typeof(promotion_json) = 'object'),
  report_template_json jsonb not null default '{}'::jsonb check (jsonb_typeof(report_template_json) = 'object'),
  fee_template_json jsonb not null default '{}'::jsonb check (jsonb_typeof(fee_template_json) = 'object'),
  created_by text not null,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code),
  unique (tenant_id, id),
  check (start_date < end_date),
  check (enrollment_start <= enrollment_end),
  check (school_opening_date between start_date and end_date)
);

create unique index if not exists uq_academic_year_one_active
  on public.academic_years (tenant_id) where status = 'active';
create index if not exists idx_academic_years_tenant_status
  on public.academic_years (tenant_id, status, start_date desc);

create table if not exists public.academic_terms (
  id bigint generated by default as identity primary key,
  academic_year_id bigint not null,
  tenant_id text not null,
  name text not null check (char_length(name) between 2 and 40),
  code text not null check (char_length(code) between 1 and 12),
  position smallint not null check (position between 1 and 6),
  start_date date not null,
  end_date date not null,
  composition_start date not null,
  composition_end date not null,
  report_publication_date date not null,
  status text not null default 'open' check (status in ('open','closed')),
  reports_published boolean not null default false,
  unique (academic_year_id, code),
  unique (tenant_id, academic_year_id, id),
  foreign key (tenant_id, academic_year_id)
    references public.academic_years(tenant_id, id) on delete cascade,
  check (start_date <= end_date),
  check (composition_start between start_date and end_date),
  check (composition_end between composition_start and end_date),
  check (report_publication_date >= composition_end)
);
create index if not exists idx_academic_terms_year_position
  on public.academic_terms (tenant_id, academic_year_id, position);

create table if not exists public.academic_year_audit (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  academic_year_id bigint not null,
  actor_email text not null,
  action text not null,
  previous_status text not null default '',
  new_status text not null default '',
  reason text not null default '',
  details_json jsonb not null default '{}'::jsonb check (jsonb_typeof(details_json) = 'object'),
  created_at timestamptz not null default now(),
  foreign key (tenant_id, academic_year_id)
    references public.academic_years(tenant_id, id) on delete cascade
);
create index if not exists idx_academic_audit_year_created
  on public.academic_year_audit (tenant_id, academic_year_id, created_at desc);

create table if not exists public.academic_year_permissions (
  tenant_id text not null references public.tenants(id) on delete cascade,
  user_email text not null,
  can_manage boolean not null default true,
  can_reopen boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, user_email)
);

create table if not exists public.academic_structure_items (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  academic_year_id bigint not null,
  item_type text not null check (item_type in ('cycle','level','stream','section','class','subject')),
  code text not null check (char_length(code) between 1 and 20),
  name text not null check (char_length(name) between 2 and 80),
  parent_id bigint,
  settings_json jsonb not null default '{}'::jsonb check (jsonb_typeof(settings_json) = 'object'),
  sort_order integer not null default 0,
  unique (academic_year_id, item_type, code),
  unique (tenant_id, academic_year_id, id),
  foreign key (tenant_id, academic_year_id)
    references public.academic_years(tenant_id, id) on delete cascade,
  foreign key (tenant_id, academic_year_id, parent_id)
    references public.academic_structure_items(tenant_id, academic_year_id, id) on delete cascade
);
create index if not exists idx_academic_structure_tree
  on public.academic_structure_items (tenant_id, academic_year_id, item_type, sort_order);
create index if not exists idx_academic_structure_parent
  on public.academic_structure_items (tenant_id, academic_year_id, parent_id) where parent_id is not null;

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  academic_year_id bigint not null,
  student_id bigint not null,
  class_id bigint,
  status text not null default 'pending' check (status in ('pending','promoted','repeated','transferred','withdrawn','excluded')),
  decision_reason text not null default '',
  enrolled_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (academic_year_id, student_id),
  foreign key (tenant_id, academic_year_id)
    references public.academic_years(tenant_id, id) on delete restrict,
  foreign key (tenant_id, student_id)
    references public.students(tenant_id, id) on delete cascade,
  foreign key (tenant_id, academic_year_id, class_id)
    references public.academic_structure_items(tenant_id, academic_year_id, id) on delete restrict
);
create index if not exists idx_enrollments_student
  on public.enrollments (tenant_id, student_id, academic_year_id desc);
create index if not exists idx_enrollments_class
  on public.enrollments (tenant_id, academic_year_id, class_id, status);

create table if not exists public.report_card_versions (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  academic_year_id bigint not null,
  student_id bigint not null,
  version integer not null check (version > 0),
  snapshot_json jsonb not null check (jsonb_typeof(snapshot_json) = 'object'),
  status text not null default 'draft' check (status in ('draft','published')),
  correction_reason text not null default '',
  created_by text not null,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (academic_year_id, student_id, version),
  foreign key (tenant_id, academic_year_id)
    references public.academic_years(tenant_id, id) on delete restrict,
  foreign key (tenant_id, student_id)
    references public.students(tenant_id, id) on delete cascade,
  check ((status = 'draft' and published_at is null) or (status = 'published' and published_at is not null))
);
create index if not exists idx_report_cards_student_year
  on public.report_card_versions (tenant_id, student_id, academic_year_id, version desc);

alter table public.resources add column if not exists academic_year_id bigint;
create index if not exists idx_resources_academic_year
  on public.resources (tenant_id, academic_year_id, resource_type)
  where academic_year_id is not null;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'resources_tenant_academic_year_fkey') then
    alter table public.resources add constraint resources_tenant_academic_year_fkey
      foreign key (tenant_id, academic_year_id)
      references public.academic_years(tenant_id, id) on delete restrict;
  end if;
end $$;

create or replace function public.set_school_ing_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke all on function public.set_school_ing_updated_at() from public, anon, authenticated;

drop trigger if exists trg_academic_years_updated_at on public.academic_years;
create trigger trg_academic_years_updated_at before update on public.academic_years
for each row execute function public.set_school_ing_updated_at();
drop trigger if exists trg_academic_permissions_updated_at on public.academic_year_permissions;
create trigger trg_academic_permissions_updated_at before update on public.academic_year_permissions
for each row execute function public.set_school_ing_updated_at();
drop trigger if exists trg_enrollments_updated_at on public.enrollments;
create trigger trg_enrollments_updated_at before update on public.enrollments
for each row execute function public.set_school_ing_updated_at();

create or replace function public.reject_academic_audit_mutation()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  raise exception 'academic year audit records are immutable';
end;
$$;
revoke all on function public.reject_academic_audit_mutation() from public, anon, authenticated;
drop trigger if exists trg_academic_audit_immutable on public.academic_year_audit;
create trigger trg_academic_audit_immutable before update or delete on public.academic_year_audit
for each row execute function public.reject_academic_audit_mutation();

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'academic_years','academic_terms','academic_year_audit',
    'academic_year_permissions','academic_structure_items',
    'enrollments','report_card_versions'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('drop policy if exists server_only on public.%I', table_name);
    execute format('create policy server_only on public.%I for all to anon, authenticated using (false) with check (false)', table_name);
  end loop;
end $$;

revoke all on all sequences in schema public from anon, authenticated;

insert into public.academic_year_permissions (tenant_id, user_email, can_manage, can_reopen)
select tenant_id, lower(email), true, true
from public.users
where role = 'admin' and active = true
on conflict (tenant_id, user_email) do update
set can_manage = excluded.can_manage;
