import { z } from "zod";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { submissionSelect } from "@/lib/assignment-submissions";
import { jsonError } from "@/lib/http";
import { securityOriginValid } from "@/lib/security";
const idSchema=z.coerce.number().int().positive(),link=z.string().trim().max(1000).refine(value=>!value||/^https?:\/\//i.test(value),"Attachment must be an HTTP(S) link");
const studentSchema=z.object({content:z.string().trim().max(10000),attachmentUrl:link,status:z.enum(["draft","submitted"])}).refine(value=>value.status!=="submitted"||Boolean(value.content||value.attachmentUrl),{message:"Add an answer or attachment before submitting"});
const reviewSchema=z.object({status:z.enum(["submitted","reviewed","returned"]),score:z.union([z.coerce.number().min(0).max(100),z.null()]).optional(),feedback:z.string().trim().max(4000).default("")});
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const session=await getSession();if(!session)return jsonError("Authentication required",401);if(!securityOriginValid(request,session.tenantId))return jsonError("Invalid request origin",403);const id=idSchema.safeParse((await params).id);if(!id.success)return jsonError("Invalid submission",400);const current=db.prepare("SELECT student_email studentEmail,status FROM assignment_submissions WHERE id=? AND tenant_id=?").get(id.data,session.tenantId) as {studentEmail:string;status:string}|undefined;if(!current)return jsonError("Submission not found",404);if(session.role==="student"){if(current.studentEmail!==session.userId)return jsonError("You can only edit your own submission",403);if(current.status==="reviewed")return jsonError("A reviewed submission can no longer be changed",409);const body=studentSchema.safeParse(await request.json().catch(()=>null));if(!body.success)return jsonError("Invalid submission",400,body.error.flatten());db.prepare("UPDATE assignment_submissions SET content=?,attachment_url=?,status=?,submitted_at=CASE WHEN ?='submitted' THEN COALESCE(submitted_at,CURRENT_TIMESTAMP) ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND student_email=?").run(body.data.content,body.data.attachmentUrl,body.data.status,body.data.status,id.data,session.tenantId,session.userId)}else if(session.role==="admin"||session.role==="teacher"){const body=reviewSchema.safeParse(await request.json().catch(()=>null));if(!body.success)return jsonError("Invalid review",400,body.error.flatten());db.prepare("UPDATE assignment_submissions SET status=?,score=?,feedback=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?").run(body.data.status,body.data.score??null,body.data.feedback,id.data,session.tenantId)}else return jsonError("Submission edit access denied",403);return Response.json({data:db.prepare(`${submissionSelect} WHERE s.id=? AND s.tenant_id=?`).get(id.data,session.tenantId)})}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const session=await getSession();if(!session)return jsonError("Authentication required",401);if(!securityOriginValid(request,session.tenantId))return jsonError("Invalid request origin",403);const id=idSchema.safeParse((await params).id);if(!id.success)return jsonError("Invalid submission",400);const row=db.prepare("SELECT student_email studentEmail,status FROM assignment_submissions WHERE id=? AND tenant_id=?").get(id.data,session.tenantId) as {studentEmail:string;status:string}|undefined;if(!row)return jsonError("Submission not found",404);if(session.role==="student"&&(row.studentEmail!==session.userId||row.status!=="draft"))return jsonError("Only your own draft submission can be deleted",403);if(session.role!=="student"&&session.role!=="admin")return jsonError("Submission delete access denied",403);db.prepare("DELETE FROM assignment_submissions WHERE id=? AND tenant_id=?").run(id.data,session.tenantId);return new Response(null,{status:204})}
